remote_theme: mmistakes/jekyll-theme-basically-basic

title: Homebridge Automower Platform

markdown: kramdown

exclude: [ '.vscode', 'docs.code-workspace', 'Gemfile', 'Gemfile.lock' ]

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme