lang: en-US
title: Homebridge Automower Platform
description: A plugin to use the Husqvuarna Automower with Homebridge

author:
  name: Jeff Winn

# This will turn on the site built in hooks, but the token comes from secrets.
google_analytics: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/jekyll-theme-basically-basic
permalink: pretty

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-environment-variables

collections:
  getting_started:
    output: true
    permalink: /getting-started/:path
  extras:
    output: true
    permalink: /:collection/:path
  kb:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      type: getting_started
    values:
      layout: post
      read_time: true
  - scope:
      type: extras
    values:
      layout: post
      read_time: true
  - scope:
      type: kb
    values:
      layout: kb_article
      read_time: true
