remote_theme: mmistakes/jekyll-theme-basically-basic

lang: en-US
title: Homebridge Automower Platform
description: A plugin to use the Husqvuarna Automower with Homebridge

author:
  name: Jeff Winn

permalink: pretty
markdown: kramdown

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

collections:
  getting_started:
    output: true
    permalink: /getting-started/:path/

defaults:
  - scope:
      type: getting_started
    values:
      layout: post
      read_time: true