# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  pull_request:
    types: [opened, reopened]
  push:
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron: '0 0 1 */1 *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See LTS versions supported: https://nodejs.org/en/about/releases/
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
      
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - run: npm ci
    - run: npm run release

    - name: Scan with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Check Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@v1.1.0

      # Force to fail step after specific time
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}